# version: '3'

# services:
#   db:
#     image: postgres
#     environment:
#       POSTGRES_USER: yourusername
#       POSTGRES_PASSWORD: yourpassword
#       POSTGRES_DB: yourdatabase
#       DB_HOST
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   redis:
#     image: redis:alpine
#     ports:
#       - "6379:6379"

#   backend_rds:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: python backend_rds/manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#       - redis
#     environment:
#       DJANGO_SETTINGS_MODULE: backend_rds.settings

#   backend_redis:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: python backend_redis/manage.py runserver 0.0.0.0:8001
#     volumes:
#       - .:/app
#     ports:
#       - "8001:8001"
#     depends_on:
#       - redis
#     environment:
#       DJANGO_SETTINGS_MODULE: backend_redis.settings

# volumes:
#   postgres_data:


version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST} 
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:alpine
    # ports:
    #   - "6379:6379"
    environment: 
      REDIS_URL: "redis://${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}"

  backend_rds:
    build:
      context: ./backend_rds
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    # environment:
    #   DB_HOST: db
    #   DB_PORT: 5432
    #   DB_NAME: your_db
    #   DB_USER: your_user
    #   DB_PASSWORD: your_password

  backend_redis:
    build:
      context: ./backend_redis
      dockerfile: Dockerfile
    # volumes:
    #   - ./data:/app
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_password
      - REDIS_DB=db
      - CORS_ALLOWED_ORIGINS='http://localhost', '127.0.0.1', '0.0.0.0','*'
      # - CORS_ORIGIN_WHITELIST="https://localhost:3000"
      - CORS_ALLOW_ALL_ORIGINS=True
      - CORS_ALLOW_CREDENTIALS=True
    #   REDIS_HOST: redis
    #   REDIS_PORT: 6379

volumes:
  postgres_data:
