version: '3'
services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file: 
      - .env

  backend_redis:
    container_name: backend_redis
    build:
      context: ./backend_redis
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file: 
      - .env
