version: '3'
services:
  db:
    image: postgres
    env_file: 
      - .env
    # environment:
    #   - POSTGRES_USER=${DB_USER}
    #   - POSTGRES_PASSWORD=${DB_PASSWORD}
    #   - POSTGRES_HOST=${DB_HOST} 
    #   - POSTGRES_PORT=${DB_PORT}
    #   - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    env_file: 
      - .env
    environment: 
     - REDIS_URL="redis://${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}"

  backend_rds:
    container_name: backend_rds
    build:
      context: ./backend_rds
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: 
      - .env

  backend_redis:
    container_name: backend_redis
    build:
      context: ./backend_redis
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file: 
      - .env

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:80"

volumes:
  postgres_data:
